apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication2-deployment
  labels:
    app: webapplication2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapplication2
  template:
    metadata:
      labels:
        app: webapplication2
    spec:
      containers:
      - name: webapplication2
        image: aksregus.azurecr.io/webapplication2:dev
        ports:
        - containerPort: 8085
